### ISSUE TITLE
Want to turn this into a .org?

### ISSUE THREAD

**Issue by jrdnrch** [s9a/s9a.github.io#53]
This seems like a good way to start a collective what do you think?

**Comment by ryanve** [comment]
got [s9a.org](https://s9a.org) last nite plus [s9a.page](https://s9a.page) to test if page domains work on github pages and yes they do #63

**Comment by jrdnrich** [comment]
Those are both good domains. Maybe hold on to the org for any open source projects, tools or community or public service initiatives etc..

**Comment by ryanve** [comment]
https://s9a.page/natal
